name: CLA Check with Cache and Signature Debugging

on:
  issue_comment:
    types:
      - "created"
  pull_request_target:
    types:
      - "opened"
      - "closed"
      - "synchronize"

jobs:
  cla-assistant:
    runs-on: "ubuntu-latest"
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4
        name: Checkout repository

      # Debugging: Print GitHub event information
      - name: "Print GitHub event details for debugging"
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Actor: ${{ github.actor }}"
          echo "Comment Body: ${{ github.event.comment.body }}"
      
      # Clear the cache if caching is suspected
      - name: "Clear previous GitHub Actions cache (if any)"
        run: |
          echo "Clearing any cached data from previous runs."
          rm -rf ${{ github.workspace }}/.github/cla-cache/*

      # Debug: Ensure the signatures.json is updated
      - name: "Check signatures.json content"
        run: |
          echo "Contents of signatures.json:"
          cat etc/cla-signatures/signatures.json